### ISSUE TITLE
¿Elimino la parte de contacto al final de socios institucionales?

### ISSUE THREAD

**Issue by danielacos** [BoletinSEMA/boletin22#12]

**Comment by rrgalvan** [comment]
¿Qué ha pasado (*no description provided*)? :-)

**Comment by danielacos** [comment]
Perdón. Al final de la parte de socios institucionales aparece lo mismo que abajo de la portada (nombre de los editores, contacto...), habría que eliminarlo de esta parte, ¿verdad?

**Comment by rrgalvan** [comment]
Es verdad, habrá que eliminarlo.

También habría que eliminar (en todas las secciones) los caracteres 

"_____________________________________ ◇◇◇_____________________"

que quedan un poco feos, y sustituirlos por

<hr/>

De acuerdo con https://www.w3schools.com/tags/tag_hr.asp, "The <hr> element is used to separate content (or define a change) in an HTML page."

@GloriaAlmozara, ¿avisas a la gente de esto? O, mejor, voy a asignarlo como tarea

**Comment by danielacos** [comment]
De acuerdo, cambio todo eso y aviso a los demás. Muchas gracias.

**Comment by rrgalvan** [comment]
Pues muchas gracias!!

En general, habría que sustituir todos los caracteres ________ por  hr

**Comment by danielacos** [comment]
Perfecto ;)
